// Generated by brand/icons/generate.ts from the drawings in brand/icons. Run it again
// rather than editing this file.

import { stroke } from './space';

/**
 * The symbols of the set. The set is closed, so a screen cannot ask for a drawing nobody made.
 */
export type IconName =
  | 'calendar'
  | 'chart'
  | 'check'
  | 'chevron'
  | 'close'
  | 'delete'
  | 'drop'
  | 'edit'
  | 'energy'
  | 'export'
  | 'lock'
  | 'mood'
  | 'note'
  | 'pain'
  | 'plus'
  | 'ring'
  | 'search'
  | 'settings'
  | 'shield'
  | 'sleep'
  | 'spotting'
  | 'sun'
  | 'temperature'
  | 'weight';

/**
 * A drawing and the grid it was laid out on. The body is markup rather than one path, because
 * several of them are drawn from more than one shape.
 */
export interface Icon {
  readonly name: IconName;
  /** The grid the drawing is laid out on, in points, on both axes. */
  readonly size: number;
  readonly strokeWidth: number;
  /** The drawing, as the markup inside the canvas. */
  readonly body: string;
}

/**
 * The grid every drawing shares, in points. A drawing laid out on another grid does not match the
 * stroke width of the ones beside it.
 */
export const ICON_SIZE = 24;

/**
 * The corner a rectangle inside an icon is rounded to, on the 24 unit grid the set is drawn on.
 * The design system's smallest corner is 4, which is a box on a screen rather than a detail inside
 * a drawing, so the grid keeps its own.
 */
export const ICON_CORNER = 2;

/** The set as data, so a test can walk every drawing without naming them one at a time. */
export const iconNames: readonly IconName[] = [
  'calendar',
  'chart',
  'check',
  'chevron',
  'close',
  'delete',
  'drop',
  'edit',
  'energy',
  'export',
  'lock',
  'mood',
  'note',
  'pain',
  'plus',
  'ring',
  'search',
  'settings',
  'shield',
  'sleep',
  'spotting',
  'sun',
  'temperature',
  'weight',
];

/**
 * Generated from the drawings in `brand/icons`. Run the generator again rather than editing a body
 * here, because the next run writes over it.
 */
export const icons: Readonly<Record<IconName, Icon>> = {
  calendar: {
    name: 'calendar',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<rect x="3.5" y="5.25" width="17" height="15.25" rx="2" /> <path d="M3.5 10h17" /> <path d="M8.25 3.5v3.5" /> <path d="M15.75 3.5v3.5" />',
  },
  chart: {
    name: 'chart',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M3.25 17.5h3.5V9.75h3.5v7.75h3.5V6.5h3.5v11h3.5" />',
  },
  check: {
    name: 'check',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M4.75 12.6 9.9 17.75 19.25 6.5" />',
  },
  chevron: {
    name: 'chevron',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M9.5 5.25 16.25 12 9.5 18.75" />',
  },
  close: {
    name: 'close',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M6.5 6.5 17.5 17.5" /> <path d="M17.5 6.5 6.5 17.5" />',
  },
  delete: {
    name: 'delete',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M4.5 6.75h15" /> <path d="M9.5 6.75V4.5h5v2.25" /> <path d="M6.75 6.75 7.6 19.4a1.6 1.6 0 0 0 1.6 1.35h5.6a1.6 1.6 0 0 0 1.6-1.35l.85-12.65" /> <path d="M10.5 10.5v6.5" /> <path d="M13.5 10.5v6.5" />',
  },
  drop: {
    name: 'drop',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M12 3.2c0 0-6.6 6.9-6.6 11.15a6.6 6.6 0 0 0 13.2 0C18.6 10.1 12 3.2 12 3.2Z" />',
  },
  edit: {
    name: 'edit',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M4.25 7.25h10.5" /> <path d="M4.25 12h6.5" /> <path d="M4.25 16.75h4.5" /> <path d="m18.9 10.85 2.25 2.25-5.6 5.6-2.85.6.6-2.85z" /> <path d="m17.25 12.5 2.25 2.25" />',
  },
  energy: {
    name: 'energy',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M13.4 2.75 6.25 13.4h4.6L10.6 21.25l7.15-10.65h-4.6z" />',
  },
  export: {
    name: 'export',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M12 15V3.25" /> <path d="M8.25 7 12 3.25 15.75 7" /> <path d="M5 13.75v4.75a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-4.75" />',
  },
  lock: {
    name: 'lock',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<rect x="4.5" y="10.25" width="15" height="10.25" rx="2" /> <path d="M8 10.25V7.5a4 4 0 0 1 8 0v2.75" />',
  },
  mood: {
    name: 'mood',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<circle cx="12" cy="12" r="8.25" /> <path d="M8.25 13.5a4.5 4.5 0 0 0 7.5 0" />',
  },
  note: {
    name: 'note',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<rect x="4.75" y="3" width="14.5" height="18" rx="2" /> <path d="M8.5 8.25h7" /> <path d="M8.5 12h7" /> <path d="M8.5 15.75h4" />',
  },
  pain: {
    name: 'pain',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<circle cx="12" cy="12" r="1.6" /> <path d="M7.4 7.4a6.5 6.5 0 0 0 0 9.2" /> <path d="M16.6 16.6a6.5 6.5 0 0 0 0-9.2" /> <path d="M4.3 4.3a10.9 10.9 0 0 0 0 15.4" /> <path d="M19.7 19.7a10.9 10.9 0 0 0 0-15.4" />',
  },
  plus: {
    name: 'plus',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M12 5v14" /> <path d="M5 12h14" />',
  },
  ring: {
    name: 'ring',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M4.75 8.62A8 8 0 1 0 8.62 4.75" />',
  },
  search: {
    name: 'search',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<circle cx="10.75" cy="10.75" r="6.5" /> <path d="M15.6 15.6 20 20" />',
  },
  settings: {
    name: 'settings',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M3.75 8.25h11" /> <path d="M18.5 8.25h1.75" /> <path d="M3.75 15.75h5" /> <path d="M12.5 15.75h7.75" /> <circle cx="16.6" cy="8.25" r="1.9" /> <circle cx="10.6" cy="15.75" r="1.9" />',
  },
  shield: {
    name: 'shield',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M12 3.25 4.75 6v6.25c0 4.35 3 7.35 7.25 8.5 4.25-1.15 7.25-4.15 7.25-8.5V6z" /> <path d="m8.75 12.25 2.25 2.25 4.25-4.5" />',
  },
  sleep: {
    name: 'sleep',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M20.3 14.6A8.6 8.6 0 0 1 9.4 3.7 8.75 8.75 0 1 0 20.3 14.6Z" />',
  },
  spotting: {
    name: 'spotting',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M9 4.5c0 0-3.9 4.1-3.9 6.6a3.9 3.9 0 0 0 7.8 0C12.9 8.6 9 4.5 9 4.5Z" /> <circle cx="17.25" cy="9.75" r="1.5" /> <circle cx="14.25" cy="17.5" r="1.5" /> <circle cx="19" cy="16" r="1.1" />',
  },
  sun: {
    name: 'sun',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<circle cx="12" cy="12" r="4" /> <path d="M12 5.75V3.25" /> <path d="M16.42 7.58 18.19 5.81" /> <path d="M18.25 12h2.5" /> <path d="m16.42 16.42 1.77 1.77" /> <path d="M12 18.25v2.5" /> <path d="M7.58 16.42 5.81 18.19" /> <path d="M5.75 12h-2.5" /> <path d="M7.58 7.58 5.81 5.81" />',
  },
  temperature: {
    name: 'temperature',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M14 14.1V5.5a2 2 0 1 0-4 0v8.6a3.9 3.9 0 1 0 4 0Z" /> <path d="M16.75 7.5h2.25" /> <path d="M16.75 11h2.25" />',
  },
  weight: {
    name: 'weight',
    size: ICON_SIZE,
    strokeWidth: stroke.icon,
    body: '<path d="M4.25 17.25a7.75 7.75 0 1 1 15.5 0" /> <path d="M4.25 17.25h15.5" /> <path d="M12 17.25 15.5 11.5" />',
  },
};

/** A name outside the set is a drawing nobody has, so it fails here rather than on her screen. */
export function icon(name: string): Icon {
  const found: Icon | undefined = icons[name as IconName];
  if (found === undefined) {
    throw new Error(`no icon named ${name}`);
  }
  return found;
}
