#!/usr/bin/env -S node --experimental-strip-types
/**
 * The drawings are the source. This reads every file in this directory and writes the token module
 * that names them, so adding an icon is adding one file and running this again.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { colours } from '../../packages/tokens/src/colour.ts';
import { stroke } from '../../packages/tokens/src/space.ts';

const here = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = join(here, '..', '..');
const tokenModule = join(repositoryRoot, 'packages', 'tokens', 'src', 'icons.ts');
const contactSheet = join(here, 'contact-sheet.svg');

const ICON_SIZE = 24;
const SHEET_COLUMNS = 5;
const SHEET_CELL = 96;

interface Drawing {
  readonly name: string;
  readonly body: string;
}

function drawingFiles(directory: string): readonly string[] {
  return readdirSync(directory)
    .filter((file) => file.endsWith('.svg') && file !== 'contact-sheet.svg')
    .sort();
}

/** The markup between the opening and the closing svg tag, on one line. */
function bodyOf(source: string): string {
  const opened = source.indexOf('>');
  const closed = source.lastIndexOf('</svg>');
  if (opened === -1 || closed === -1 || closed < opened) {
    throw new Error('a drawing with no svg element');
  }
  return source
    .slice(opened + 1, closed)
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .join(' ');
}

function readDrawings(directory: string): readonly Drawing[] {
  return drawingFiles(directory).map((file) => ({
    name: file.replace(/\.svg$/, ''),
    body: bodyOf(readFileSync(join(directory, file), 'utf8')),
  }));
}

function moduleSource(drawings: readonly Drawing[]): string {
  const union = drawings.map((drawing) => `  | '${drawing.name}'`).join('\n');
  const list = drawings.map((drawing) => `  '${drawing.name}',`).join('\n');
  const entries = drawings
    .map(
      (drawing) =>
        `  '${drawing.name}': {\n` +
        `    name: '${drawing.name}',\n` +
        `    size: ICON_SIZE,\n` +
        `    strokeWidth: stroke.icon,\n` +
        `    body: '${drawing.body.replace(/'/g, "\\'")}',\n` +
        `  },`,
    )
    .join('\n');

  return `// Generated by brand/icons/generate.ts from the drawings in brand/icons. Run it again
// rather than editing this file.

import { stroke } from './space';

export type IconName =
${union};

export interface Icon {
  readonly name: IconName;
  /** The grid the drawing is laid out on, in points, on both axes. */
  readonly size: number;
  readonly strokeWidth: number;
  /** The drawing, as the markup inside the canvas. */
  readonly body: string;
}

export const ICON_SIZE = ${ICON_SIZE};

export const iconNames: readonly IconName[] = [
${list}
];

export const icons: Readonly<Record<IconName, Icon>> = {
${entries}
};

/** A name outside the set is a drawing nobody has, so it fails here rather than on her screen. */
export function icon(name: string): Icon {
  const found: Icon | undefined = icons[name as IconName];
  if (found === undefined) {
    throw new Error(\`no icon named \${name}\`);
  }
  return found;
}
`;
}

/** Every icon at its real size, on the ground it is drawn against, with its name under it. */
function contactSheetSource(drawings: readonly Drawing[]): string {
  const rows = Math.ceil(drawings.length / SHEET_COLUMNS);
  const width = SHEET_COLUMNS * SHEET_CELL;
  const height = rows * SHEET_CELL;
  const ground = colours.surfaceContainerLowest.value;
  const ink = colours.onSurface.value;
  const placed = drawings
    .map((drawing, index) => {
      const left = (index % SHEET_COLUMNS) * SHEET_CELL;
      const top = Math.floor(index / SHEET_COLUMNS) * SHEET_CELL;
      const drawn = `translate(${left + (SHEET_CELL - ICON_SIZE) / 2} ${top + 28})`;
      return (
        `  <g transform="${drawn}" fill="none" stroke="${ink}" stroke-width="${stroke.icon}" ` +
        `stroke-linecap="round" stroke-linejoin="round">${drawing.body}</g>\n` +
        `  <text x="${left + SHEET_CELL / 2}" y="${top + 74}" text-anchor="middle" ` +
        `font-family="monospace" font-size="9" fill="${ink}">${drawing.name}</text>`
      );
    })
    .join('\n');

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
  <rect width="${width}" height="${height}" fill="${ground}" />
${placed}
</svg>
`;
}

const drawings = readDrawings(here);
writeFileSync(tokenModule, moduleSource(drawings), 'utf8');
writeFileSync(contactSheet, contactSheetSource(drawings), 'utf8');
execFileSync('npx', ['prettier', '--write', tokenModule], {
  cwd: repositoryRoot,
  stdio: 'inherit',
});
process.stdout.write(`${drawings.length} drawings, written to packages/tokens/src/icons.ts\n`);
