#!/usr/bin/env -S node --experimental-strip-types
/**
 * The drawings are the source. This reads every drawing, holds each one to the rules in README.md,
 * and writes the token module that names them, so adding an icon is adding one file and running
 * this again. A drawing that breaks a rule is refused before anything is written.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { colours } from '../../packages/tokens/src/colour.ts';
import { stroke } from '../../packages/tokens/src/space.ts';

import { ICON_CORNER, ICON_GRID as ICON_SIZE, problemsWith } from './rules.ts';

const here = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = join(here, '..', '..');

/**
 * Where the drawings are read from, and where the two generated files go. A run that says
 * nothing gets the set this repository ships. A run that says all three gets a directory of its
 * own, so a drawing that breaks a rule can be shown to be refused without touching the set.
 */
function pathArgument(name: string, fallback: string): string {
  const at = process.argv.indexOf(`--${name}`);
  const given = at === -1 ? undefined : process.argv[at + 1];

  if (at !== -1 && given === undefined) {
    throw new Error(`--${name} names no path`);
  }

  return given === undefined ? fallback : resolve(given);
}

const drawingsFrom = pathArgument('from', here);
const tokenModule = pathArgument(
  'module',
  join(repositoryRoot, 'packages', 'tokens', 'src', 'icons.ts'),
);
const contactSheet = pathArgument('sheet', join(here, 'contact-sheet.svg'));
const SHEET_COLUMNS = 5;
const SHEET_CELL = 96;

interface Drawing {
  readonly name: string;
  readonly body: string;
}

function drawingFiles(directory: string): readonly string[] {
  return readdirSync(directory)
    .filter((file) => file.endsWith('.svg') && file !== 'contact-sheet.svg')
    .sort();
}

/** The markup between the opening and the closing svg tag, on one line. */
function bodyOf(source: string): string {
  const opened = source.indexOf('>');
  const closed = source.lastIndexOf('</svg>');
  if (opened === -1 || closed === -1 || closed < opened) {
    throw new Error('a drawing with no svg element');
  }
  return source
    .slice(opened + 1, closed)
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .join(' ');
}

function readDrawings(directory: string): readonly Drawing[] {
  return drawingFiles(directory).map((file) => ({
    name: file.replace(/\.svg$/, ''),
    body: bodyOf(readFileSync(join(directory, file), 'utf8')),
  }));
}

function moduleSource(drawings: readonly Drawing[]): string {
  const union = drawings.map((drawing) => `  | '${drawing.name}'`).join('\n');
  const list = drawings.map((drawing) => `  '${drawing.name}',`).join('\n');
  const entries = drawings
    .map(
      (drawing) =>
        `  '${drawing.name}': {\n` +
        `    name: '${drawing.name}',\n` +
        `    size: ICON_SIZE,\n` +
        `    strokeWidth: stroke.icon,\n` +
        `    body: '${drawing.body.replace(/'/g, "\\'")}',\n` +
        `  },`,
    )
    .join('\n');

  return `// Generated by brand/icons/generate.ts from the drawings in brand/icons. Run it again
// rather than editing this file.

import { stroke } from './space';

/**
 * The symbols of the set. The set is closed, so a screen cannot ask for a drawing nobody made.
 */
export type IconName =
${union};

/**
 * A drawing and the grid it was laid out on. The body is markup rather than one path, because
 * several of them are drawn from more than one shape.
 */
export interface Icon {
  readonly name: IconName;
  /** The grid the drawing is laid out on, in points, on both axes. */
  readonly size: number;
  readonly strokeWidth: number;
  /** The drawing, as the markup inside the canvas. */
  readonly body: string;
}

/**
 * The grid every drawing shares, in points. A drawing laid out on another grid does not match the
 * stroke width of the ones beside it.
 */
export const ICON_SIZE = ${ICON_SIZE};

/**
 * The corner a rectangle inside an icon is rounded to, on the 24 unit grid the set is drawn on.
 * The design system's smallest corner is 4, which is a box on a screen rather than a detail inside
 * a drawing, so the grid keeps its own.
 */
export const ICON_CORNER = ${ICON_CORNER};

/** The set as data, so a test can walk every drawing without naming them one at a time. */
export const iconNames: readonly IconName[] = [
${list}
];

/**
 * Generated from the drawings in \`brand/icons\`. Run the generator again rather than editing a body
 * here, because the next run writes over it.
 */
export const icons: Readonly<Record<IconName, Icon>> = {
${entries}
};

/** A name outside the set is a drawing nobody has, so it fails here rather than on her screen. */
export function icon(name: string): Icon {
  const found: Icon | undefined = icons[name as IconName];
  if (found === undefined) {
    throw new Error(\`no icon named \${name}\`);
  }
  return found;
}
`;
}

/** Every icon at its real size, on the ground it is drawn against, with its name under it. */
function contactSheetSource(drawings: readonly Drawing[]): string {
  const rows = Math.ceil(drawings.length / SHEET_COLUMNS);
  const width = SHEET_COLUMNS * SHEET_CELL;
  const height = rows * SHEET_CELL;
  const ground = colours.surfaceContainerLowest.value;
  const ink = colours.onSurface.value;
  const placed = drawings
    .map((drawing, index) => {
      const left = (index % SHEET_COLUMNS) * SHEET_CELL;
      const top = Math.floor(index / SHEET_COLUMNS) * SHEET_CELL;
      const drawn = `translate(${left + (SHEET_CELL - ICON_SIZE) / 2} ${top + 28})`;
      return (
        `  <g transform="${drawn}" fill="none" stroke="${ink}" stroke-width="${stroke.icon}" ` +
        `stroke-linecap="round" stroke-linejoin="round">${drawing.body}</g>\n` +
        `  <text x="${left + SHEET_CELL / 2}" y="${top + 74}" text-anchor="middle" ` +
        `font-family="monospace" font-size="9" fill="${ink}">${drawing.name}</text>`
      );
    })
    .join('\n');

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
  <rect width="${width}" height="${height}" fill="${ground}" />
${placed}
</svg>
`;
}

/** Every rule broken by any drawing in the directory, in the order the files are read. */
function problemsIn(directory: string): readonly string[] {
  return drawingFiles(directory).flatMap((file) =>
    problemsWith(file, readFileSync(join(directory, file), 'utf8')),
  );
}

const refused = problemsIn(drawingsFrom);

if (refused.length > 0) {
  for (const problem of refused) {
    process.stderr.write(`${problem}\n`);
  }
  process.stderr.write(
    `${refused.length} drawing rule(s) broken, so nothing was written. The rules are in ` +
      `brand/icons/README.md.\n`,
  );
  process.exit(1);
}

const drawings = readDrawings(drawingsFrom);
writeFileSync(tokenModule, moduleSource(drawings), 'utf8');
writeFileSync(contactSheet, contactSheetSource(drawings), 'utf8');
execFileSync('npx', ['prettier', '--write', tokenModule], {
  cwd: repositoryRoot,
  stdio: 'inherit',
});
process.stdout.write(`${drawings.length} drawings, written to ${tokenModule}\n`);
