import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { nameOf, workspaceDirectoriesOf } from '../pipeline/documentation.ts';
import { type Documented, exportsIn, reExportsIn } from './exports.ts';
import { echoOf } from './wording.ts';

export const referenceDirectory = 'docs/reference';

export const referenceIndexPath = `${referenceDirectory}/README.md`;

export const generateCommand = 'npm run generate:reference';

export const checkCommand = 'npm run check:reference';

export interface Package {
  readonly directory: string;
  readonly name: string;
}

export interface SurfaceFile {
  readonly file: string;
  readonly exports: readonly Documented[];
}

export interface Surface {
  readonly directory: string;
  readonly name: string;
  readonly page: string;
  readonly files: readonly SurfaceFile[];
  readonly symbols: readonly Documented[];
}

export type ReadFile = (file: string) => string;

export function fileReader(root: string): ReadFile {
  return (file) => readFileSync(join(root, file), 'utf8');
}

export function entryOf(directory: string): string {
  return `${directory}/src/index.ts`;
}

export function pageOf(directory: string): string {
  return `${referenceDirectory}/${directory.slice(directory.lastIndexOf('/') + 1)}.md`;
}

/**
 * A workspace that offers an index offers a surface, so a fourth package joins the reference by
 * existing rather than by being added to a list here.
 */
export function packagesUnderReference(root: string): Package[] {
  return workspaceDirectoriesOf(root)
    .filter((directory) => existsSync(join(root, entryOf(directory))))
    .map((directory) => ({ directory, name: nameOf(root, directory) }));
}

function resolvedFrom(file: string, specifier: string): string {
  if (!specifier.startsWith('.')) {
    throw new Error(
      `${file} hands on the surface of ${specifier}, which lives in another package and is documented there`,
    );
  }

  const parts = file.split('/').slice(0, -1);

  for (const step of specifier.split('/')) {
    if (step === '.') {
      continue;
    }

    if (step === '..') {
      parts.pop();
      continue;
    }

    parts.push(step);
  }

  const path = parts.join('/');

  return path.endsWith('.ts') ? path : `${path}.ts`;
}

/** Every file the index hands on, in the order it hands them on, and the index itself first. */
export function surfaceOf(held: Package, read: ReadFile): Surface {
  const waiting = [entryOf(held.directory)];
  const alreadyRead = new Set<string>();
  const files: SurfaceFile[] = [];

  while (waiting.length > 0) {
    const file = waiting.shift() as string;

    if (alreadyRead.has(file)) {
      continue;
    }

    alreadyRead.add(file);

    const contents = read(file);

    files.push({ file, exports: exportsIn(file, contents) });

    for (const specifier of reExportsIn(file, contents)) {
      waiting.push(resolvedFrom(file, specifier));
    }
  }

  return {
    directory: held.directory,
    name: held.name,
    page: pageOf(held.directory),
    files,
    symbols: files.flatMap((file) => file.exports),
  };
}

export function surfacesOf(root: string, read: ReadFile = fileReader(root)): Surface[] {
  return packagesUnderReference(root).map((held) => surfaceOf(held, read));
}

function countedSymbols(count: number): string {
  return count === 1 ? '1 exported symbol' : `${count} exported symbols`;
}

function countedFiles(count: number): string {
  return count === 1 ? '1 file' : `${count} files`;
}

export function referencePage(surface: Surface): string {
  const lines: string[] = [
    `# \`${surface.name}\``,
    '',
    `The exported surface of \`${surface.directory}\`, generated by \`${generateCommand}\`.`,
    'Nobody writes this page by hand. The prose under each symbol is the documentation comment that',
    'sits on it in the source, so this page cannot say one thing while the code says another.',
    '',
    `${countedSymbols(surface.symbols.length)}, across ${countedFiles(surface.files.length)}.`,
    '',
  ];

  for (const file of surface.files) {
    lines.push(`## \`${file.file}\``, '');

    if (file.exports.length === 0) {
      lines.push('This file exports nothing.', '');
      continue;
    }

    for (const symbol of file.exports) {
      lines.push(`### \`${symbol.name}\``, '', '```', ...symbol.signature.split('\n'), '```', '');

      if (symbol.comment !== null) {
        lines.push(...symbol.comment.split('\n'), '');
      }
    }
  }

  return lines.join('\n');
}

export function referenceIndex(surfaces: readonly Surface[]): string {
  return [
    '# The reference',
    '',
    `What each package exports, generated from the source by \`${generateCommand}\`. A readme says`,
    'what a package is for. These pages say what it offers, what each function refuses, and which',
    'values are in range.',
    '',
    ...surfaces.map(
      (surface) =>
        `- \`${surface.page.slice(referenceDirectory.length + 1)}\` is \`${surface.name}\`, ${countedSymbols(surface.symbols.length)} across ${countedFiles(surface.files.length)}.`,
    ),
    '',
    '## The three rules the pipeline enforces',
    '',
    `\`${checkCommand}\` and \`tools/pipeline/reference.test.ts\` hold these between them.`,
    '',
    'Every exported symbol carries a documentation comment. A symbol without one fails the run and',
    'is named with its file and its line.',
    '',
    'The committed page is what the generator writes. A difference of one character fails the run,',
    `names the line, and says to run \`${generateCommand}\`. So a changed signature cannot leave a`,
    'stale page behind.',
    '',
    'A comment says something the signature cannot. A comment holding no word the declaration does',
    'not already carry is refused, because it costs a reader a line and tells them nothing.',
    '',
  ].join('\n');
}

export interface Page {
  readonly path: string;
  readonly contents: string;
}

export function referencePages(surfaces: readonly Surface[]): Page[] {
  return [
    { path: referenceIndexPath, contents: referenceIndex(surfaces) },
    ...surfaces.map((surface) => ({ path: surface.page, contents: referencePage(surface) })),
  ];
}

export function whereItSits(symbol: Documented): string {
  return `${symbol.file} line ${symbol.line}`;
}

/**
 * The reference is generated from the comments, so a symbol without one leaves a heading and a
 * signature with nothing under them. The failure names every one of them, because fixing them one
 * red run at a time is how a reader learns to stop reading the list.
 */
export function undocumentedProblems(surfaces: readonly Surface[]): string[] {
  return surfaces.flatMap((surface) =>
    surface.symbols
      .filter((symbol) => symbol.comment === null)
      .map(
        (symbol) =>
          `${surface.name} exports \`${symbol.name}\` with no documentation comment, at ${whereItSits(symbol)}`,
      ),
  );
}

export function echoProblems(surfaces: readonly Surface[]): string[] {
  return surfaces.flatMap((surface) =>
    surface.symbols.flatMap((symbol) => {
      const comment = symbol.comment;

      if (comment === null || !echoOf(comment, symbol.signature).isEcho) {
        return [];
      }

      return [
        `${surface.name} documents \`${symbol.name}\` with a comment that holds no word the declaration does not, at ${whereItSits(symbol)}`,
      ];
    }),
  );
}

export function stalenessProblems(
  path: string,
  committed: string | null,
  generated: string,
): string[] {
  if (committed === null) {
    return [
      `${path} is missing, and the generator has ${generated.split('\n').length} lines to write. Run ${generateCommand}.`,
    ];
  }

  if (committed === generated) {
    return [];
  }

  const left = committed.split('\n');
  const right = generated.split('\n');
  const differing = right.findIndex((line, index) => left[index] !== line);
  const at = differing === -1 ? Math.min(left.length, right.length) : differing;

  return [
    `${path} is stale: the committed copy and the generator disagree at line ${at + 1}.`,
    `  committed: ${JSON.stringify(left[at] ?? null)}`,
    `  generated: ${JSON.stringify(right[at] ?? null)}`,
    `A signature moved, or somebody edited the page by hand. Run ${generateCommand}.`,
  ];
}

export interface ReferenceCounts {
  readonly packages: number;
  readonly symbols: number;
  readonly files: number;
}

export function referenceCounts(surfaces: readonly Surface[]): ReferenceCounts {
  return {
    packages: surfaces.length,
    symbols: surfaces.reduce((total, surface) => total + surface.symbols.length, 0),
    files: surfaces.reduce((total, surface) => total + surface.files.length, 0),
  };
}

export function referenceSummary(counts: ReferenceCounts): string {
  return `${counts.packages} packages, ${countedSymbols(counts.symbols)} across ${countedFiles(counts.files)}`;
}

/**
 * The generated pages, the symbols with no comment and the comments that say nothing, in one pass,
 * because the pipeline command and the test must not read the surface two different ways.
 */
export interface ReferenceResult {
  readonly surfaces: readonly Surface[];
  readonly pages: readonly Page[];
  readonly counts: ReferenceCounts;
  readonly problems: readonly string[];
}

export function referenceResult(root: string, read: ReadFile = fileReader(root)): ReferenceResult {
  const surfaces = surfacesOf(root, read);

  return {
    surfaces,
    pages: referencePages(surfaces),
    counts: referenceCounts(surfaces),
    problems: [...undocumentedProblems(surfaces), ...echoProblems(surfaces)],
  };
}
